version: 2.1
description: |
  custom description custom description custom description custom description custom description
display:
  home_url: https://github.com/wigryz/custom-orb
  source_url: https://github.com/wigryz/custom-orb
commands:
  greet:
    description: |
      This command echos "Hello World" using file inclusion.
    parameters:
      to:
        default: World
        description: Hello to whom?
        type: string
    steps:
      - run:
          command: |
            #!/bin/bash
            # This example uses envsubst to support variable substitution in the string parameter type.
            # https://circleci.com/docs/orbs-best-practices/#accepting-parameters-as-strings-or-environment-variables
            TO=$(circleci env subst "${PARAM_TO}")
            # If for any reason the TO variable is not set, default to "World"
            echo "Hello ${TO:-World}!"
          environment:
            PARAM_TO: <<parameters.to>>
          name: Hello Greeting
executors:
  default:
    description: |
      This is a sample executor using Docker and Node. If you want to provide a custom environment in your orb, insert your image here. If you do not require an executor, you can simply delete this directory.
    docker:
      - image: cimg/node:<<parameters.tag>>
    parameters:
      tag:
        default: lts
        description: |
          Pick a specific cimg/node image variant: https://hub.docker.com/r/cimg/node/tags
        type: string
jobs:
  hello:
    description: |
      Sample description
    executor: default
    parameters:
      to:
        default: World
        description: Hello to whom?
        type: string
    steps:
      - greet:
          to: << parameters.to >>
examples:
  example:
    description: |
      Sample example description.
    usage:
      version: "2.1"
      orbs:
        <orb-name>: <namespace>/<orb-name>@1.2.3
      workflows:
        use-my-orb:
          jobs:
            - <orb-name>/<job-name>
