version: 2.1
description: |
  This orb was created to take out common logic for building, testing and deploying java applications build with gradle.
display:
  home_url: https://github.com/wigryz/custom-orb
  source_url: https://github.com/wigryz/custom-orb

# probably good idea would be to split those commands into small ones, to have possibility to override those commands
commands:
  build-with-gradle:
    description: |
      This command runs tests, compiles application and copies war into deployment folder.
      Deployment folder is stored as artifacts. It is also persisted in workspace.
    steps:
      - run:
          name: "Run tests"
          command: gradle test
      - run:
          name: "Compile application"
          command: gradle assemble
      - run:
          name: "gradle war"
          command: gradle war
      - run:
          name: "Copy war file into ./deployment directory"
          command: gradle copyWarFileToDeployment
      - store_artifacts:
          path: ~/workspace/deployment/
      - run:
          name: "List all files in directory ./workspace/deployment"
          command: ls -lA ~/workspace/deployment
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - deployment
executors:
  default:
    description: |
      If you want to provide a custom environment in your orb, insert your image here. If you do not require an executor, you can simply delete this directory.
    docker:
      - image: gradle:<<parameters.tag>>
    parameters:
      tag:
        default: 8.5-jdk21
        description: |
          Pick a specific gradle image variant: https://hub.docker.com/_/gradle/tags
          Keep in mind that this image should have ssh and scp installed.
        type: string

jobs:
  custom-java-build-with-gradle:
    description: |
      Sample description
    executor: default
    steps:
      - build-with-gradle

examples:
  example:
    description: |
      Sample example description.
    usage:
      version: "2.1"
      orbs:
        <orb-name>: <namespace>/<orb-name>@1.2.3
      workflows:
        use-my-orb:
          jobs:
            - <orb-name>/<job-name>
