version: 2.1
setup: true
orbs:
  circleci-cli: circleci/circleci-cli@0.1.9

jobs:
  validate:
    working_directory: ~/workspace
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - checkout:
          path: ~/workspace
      - attach_workspace:
          at: ~/
      - circleci-cli/install
      - run:
          name: "Run validation"
          command: circleci orb validate orb.yml
      - run:
          name: "ls"
          command: |
            pwd
            ls -al
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - .
  publish:
    working_directory: ~/workspace
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: "Setup circleci"
          command: |
            circleci setup --no-prompt --token $CIRCLECI_API_TOKEN
      - run:
          name: "ls"
          command: |
            pwd
            ls -al
      - run:
          name: "Publish new version"
          command: |
            version=1.0.3
            circleci orb publish orb.yml << parameters.ORB_NAME >>@$version
    parameters:
      ORB_NAME:
        type: string
        default: custom-namespace/custom-orb

workflows:
  version: 2
  validate-and-publish:
    jobs:
      - validate
      - hold-deployment:
          type: approval
          requires:
            - validate
      - publish:
          requires:
            - hold-deployment
